# Generated by Django 5.1.1 on 2024-09-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=250)),
                ('Descripcion', models.TextField(blank=True)),
                ('Fecha', models.DateField()),
                ('Completado', models.BooleanField(default=False)),
            ],
        ),
    ]
